#!/usr/bin/env bash
# Indefinitely writes I am alive! to /tmp/my_process
# Between every message the program pauses for 2 seconds

file="/tmp/my_process"

while true; do
  echo "I am alive!" >> "$file"
  sleep 2
done
