#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every message, the program should pause for 2 seconds

file="/tmp/my_process"

while true; do
  echo "I am alive!" >> "$file"
  sleep 2
done
